/*
 * Evan Robertson
 * October 3rd
 * Calculates total with tax for various items the user purchases
 */

package purchases;

import java.text.*;

/**
 *
 * @author evrob0095
 */
public class purcahses extends javax.swing.JFrame {
    
    
    
    
    

    
    public purcahses() {
        initComponents();
        
        //Start with all inputs having 0
        keyboardInputQuantity.setText("0");
        mouseInputQuantity.setText("0");
        headphoneInputQuantity.setText("0");
        speakerInputQuantity.setText("0");
        monitorInputQuantity.setText("0");
        chairInputQuantity.setText("0");
        windowsInputQuantity.setText("0");
        ethernetInputQuantity.setText("0");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        keyboardInputQuantity = new javax.swing.JTextField();
        mouseInputQuantity = new javax.swing.JTextField();
        headphoneInputQuantity = new javax.swing.JTextField();
        speakerInputQuantity = new javax.swing.JTextField();
        monitorInputQuantity = new javax.swing.JTextField();
        chairInputQuantity = new javax.swing.JTextField();
        windowsInputQuantity = new javax.swing.JTextField();
        ethernetInputQuantity = new javax.swing.JTextField();
        calculation = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        keyboardPrice = new javax.swing.JLabel();
        mousePrice = new javax.swing.JLabel();
        headphonePrice = new javax.swing.JLabel();
        speakerPrice = new javax.swing.JLabel();
        monitorPrice = new javax.swing.JLabel();
        chairPrice = new javax.swing.JLabel();
        networkPrice = new javax.swing.JLabel();
        windowsPrice = new javax.swing.JLabel();
        subTotal = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.add(keyboardInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 29, -1));
        panel.add(mouseInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 29, -1));

        headphoneInputQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headphoneInputQuantityActionPerformed(evt);
            }
        });
        panel.add(headphoneInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 29, -1));
        panel.add(speakerInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 29, -1));
        panel.add(monitorInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 79, 29, -1));
        panel.add(chairInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 110, 29, -1));
        panel.add(windowsInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 141, 29, -1));
        panel.add(ethernetInputQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 172, 29, -1));

        calculation.setText("Calculate Cost");
        calculation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculationActionPerformed(evt);
            }
        });
        panel.add(calculation, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 203, 124, 34));

        Title.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        Title.setText("Computer Center");
        panel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, -1));

        keyboardPrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        keyboardPrice.setText("Keyboard          $30.00");
        panel.add(keyboardPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        mousePrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        mousePrice.setText("Mouse                $20.00");
        panel.add(mousePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        headphonePrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        headphonePrice.setText("Headphones    $75.00");
        panel.add(headphonePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        speakerPrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        speakerPrice.setText("Speakers           $25.00");
        panel.add(speakerPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        monitorPrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        monitorPrice.setText("Monitor             $250.00");
        panel.add(monitorPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        chairPrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        chairPrice.setText("Gaming Chair  $399.99");
        panel.add(chairPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        networkPrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        networkPrice.setText("Network Cord $35.00");
        panel.add(networkPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        windowsPrice.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        windowsPrice.setText("Windows 10     $120.00");
        panel.add(windowsPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        subTotal.setFont(new java.awt.Font("SerifaDEE", 0, 18)); // NOI18N
        subTotal.setText("Subtotal: $0.00");
        panel.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, 20));

        totalLabel.setFont(new java.awt.Font("SerifaDEE", 0, 18)); // NOI18N
        totalLabel.setText("Total: $0.00");
        panel.add(totalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        taxLabel.setFont(new java.awt.Font("SerifaDEE", 0, 18)); // NOI18N
        taxLabel.setText("Tax: $0.00");
        panel.add(taxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/purchases/download (13).jpg"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headphoneInputQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headphoneInputQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headphoneInputQuantityActionPerformed

    private void calculationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculationActionPerformed
        
        //Variables
        int keyboardQuantity;
        int mouseQuantity;
        int headphoneQuantity;
        int speakerQuantity;
        int monitorQuantity;
        int chairQuantity;
        int windowsQuantity;
        int ethernetQuantity;
        double taxTotal;
        double subtotal;
        double total;
        
        //Constants
        final int KEYBOARD_PRICE = 30;
        final int MOUSE_PRICE = 20;
        final int HEADPHONE_PRICE = 75;
        final int SPEAKER_PRICE = 25;
        final int MONITOR_PRICE = 250;
        final double CHAIR_PRICE = 399.99;
        final int WINDOWS_PRICE = 120;
        final int ETHERNET_PRICE = 35;
        final double TAX = 1.13;
        
        //Decimal Format
        DecimalFormat x = new DecimalFormat("$#,###,###.00");
        
        //Get input text from user
        keyboardQuantity = Integer.parseInt(keyboardInputQuantity.getText());
        mouseQuantity = Integer.parseInt(mouseInputQuantity.getText());
        headphoneQuantity = Integer.parseInt(headphoneInputQuantity.getText());
        speakerQuantity = Integer.parseInt(speakerInputQuantity.getText());
        monitorQuantity = Integer.parseInt(monitorInputQuantity.getText());
        chairQuantity = Integer.parseInt(chairInputQuantity.getText());
        windowsQuantity = Integer.parseInt(windowsInputQuantity.getText());
        ethernetQuantity = Integer.parseInt(ethernetInputQuantity.getText());
        
        
        //Calculations
        subtotal = (keyboardQuantity*KEYBOARD_PRICE) + (mouseQuantity*MOUSE_PRICE) + (headphoneQuantity*HEADPHONE_PRICE) + (speakerQuantity*SPEAKER_PRICE) + (monitorQuantity*MONITOR_PRICE) + (chairQuantity*CHAIR_PRICE) + (windowsQuantity*WINDOWS_PRICE) + (ethernetQuantity*ETHERNET_PRICE);
        
        taxTotal = (subtotal*0.13);
        
        total = (subtotal*TAX);
        
        //Output Totals
        subTotal.setText("Subtotal: " + x.format(subtotal));
        taxLabel.setText("Tax: " + x.format(taxTotal));
        totalLabel.setText("Total: " + x.format(total));
        
        //Reset Input numbers
        keyboardInputQuantity.setText("0");
        mouseInputQuantity.setText("0");
        headphoneInputQuantity.setText("0");
        speakerInputQuantity.setText("0");
        monitorInputQuantity.setText("0");
        chairInputQuantity.setText("0");
        windowsInputQuantity.setText("0");
        ethernetInputQuantity.setText("0");
    }//GEN-LAST:event_calculationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purcahses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purcahses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purcahses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purcahses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purcahses().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton calculation;
    private javax.swing.JTextField chairInputQuantity;
    private javax.swing.JLabel chairPrice;
    private javax.swing.JTextField ethernetInputQuantity;
    private javax.swing.JTextField headphoneInputQuantity;
    private javax.swing.JLabel headphonePrice;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField keyboardInputQuantity;
    private javax.swing.JLabel keyboardPrice;
    private javax.swing.JTextField monitorInputQuantity;
    private javax.swing.JLabel monitorPrice;
    private javax.swing.JTextField mouseInputQuantity;
    private javax.swing.JLabel mousePrice;
    private javax.swing.JLabel networkPrice;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField speakerInputQuantity;
    private javax.swing.JLabel speakerPrice;
    private javax.swing.JLabel subTotal;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField windowsInputQuantity;
    private javax.swing.JLabel windowsPrice;
    // End of variables declaration//GEN-END:variables
}
